-- Latest Poonggo snapshot per streamer and month.
CREATE TABLE IF NOT EXISTS public.poonggo_monthly_snapshots (
  year_month TEXT NOT NULL,
  streamer_id UUID NOT NULL REFERENCES public.streamers(id) ON DELETE CASCADE,
  soop_id TEXT NOT NULL REFERENCES public.streamers(soop_id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  profile_image_url TEXT,
  total_stars INT NOT NULL DEFAULT 0,
  broadcast_hours NUMERIC(10,1) NOT NULL DEFAULT 0,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (year_month, streamer_id),
  UNIQUE (year_month, soop_id)
);

ALTER TABLE public.poonggo_monthly_snapshots ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.poonggo_monthly_snapshots TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.poonggo_monthly_snapshots FROM anon, authenticated;
DROP POLICY IF EXISTS "Public can read Poonggo monthly snapshots" ON public.poonggo_monthly_snapshots;
CREATE POLICY "Public can read Poonggo monthly snapshots"
  ON public.poonggo_monthly_snapshots FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.poonggo_sync_runs (
  window_start TIMESTAMPTZ NOT NULL,
  shard_index SMALLINT NOT NULL CHECK (shard_index BETWEEN 0 AND 4),
  status TEXT NOT NULL,
  requested_count INT NOT NULL DEFAULT 0,
  fetched_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  duration_ms INT NOT NULL DEFAULT 0,
  error_message TEXT,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (window_start, shard_index)
);

ALTER TABLE public.poonggo_sync_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.poonggo_sync_runs FROM anon, authenticated;

-- Seed the current 222-streamer roster. Reapplying updates metadata without losing ids.
INSERT INTO public.crews (name, category, display_order)
VALUES
  ('더블비', 'star', 0),
  ('뉴켓슬', 'star', 1),
  ('캄몬', 'star', 2),
  ('케이대', 'star', 3),
  ('JSA', 'star', 4),
  ('광준', 'star', 5),
  ('드림즈', 'star', 6),
  ('와플대', 'star', 7),
  ('BGM', 'star', 8),
  ('마범대', 'star', 9),
  ('흑카데미', 'star', 10),
  ('DM', 'star', 11),
  ('신세계', 'star', 12),
  ('소병대', 'star', 13)
ON CONFLICT (name) DO NOTHING;

WITH roster(soop_id, nickname, profile_image_url, crew_name) AS (
  VALUES
  ('suji84', '두디', 'https://profile.img.sooplive.co.kr/LOGO/su/suji84/suji84.jpg', '더블비'),
  ('rlekfu6', '박재혁', 'https://profile.img.sooplive.co.kr/LOGO/rl/rlekfu6/rlekfu6.jpg', '더블비'),
  ('pokimasiso', '또해영', 'https://profile.img.sooplive.co.kr/LOGO/po/pokimasiso/pokimasiso.jpg', '더블비'),
  ('dptmfl1258', '예슬', 'https://profile.img.sooplive.co.kr/LOGO/dp/dptmfl1258/dptmfl1258.jpg', '더블비'),
  ('jiinii000', '밥새', 'https://profile.img.sooplive.co.kr/LOGO/ji/jiinii000/jiinii000.jpg', '더블비'),
  ('palko1', '신상문', 'https://profile.img.sooplive.co.kr/LOGO/pa/palko1/palko1.jpg', '더블비'),
  ('mwhdgus', '윤진규', 'https://profile.img.sooplive.co.kr/LOGO/mw/mwhdgus/mwhdgus.jpg', '더블비'),
  ('aram1213', '아라미', 'https://profile.img.sooplive.co.kr/LOGO/ar/aram1213/aram1213.jpg', '더블비'),
  ('jungym0116', '아링', 'https://profile.img.sooplive.co.kr/LOGO/ju/jungym0116/jungym0116.jpg', '더블비'),
  ('kysvic2', '유체리', 'https://profile.img.sooplive.co.kr/LOGO/ky/kysvic2/kysvic2.jpg', '더블비'),
  ('jihoon002', '박수범', 'https://profile.img.sooplive.co.kr/LOGO/ji/jihoon002/jihoon002.jpg', '더블비'),
  ('roa0216', '허로아', 'https://profile.img.sooplive.co.kr/LOGO/ro/roa0216/roa0216.jpg', '더블비'),
  ('kjhanna824', '미진이', 'https://profile.img.sooplive.co.kr/LOGO/kj/kjhanna824/kjhanna824.jpg', '더블비'),
  ('yuzzzz', '유즈', 'https://profile.img.sooplive.co.kr/LOGO/yu/yuzzzz/yuzzzz.jpg', '뉴켓슬'),
  ('diniowo', '막내현진', 'https://profile.img.sooplive.co.kr/LOGO/di/diniowo/diniowo.jpg', '뉴켓슬'),
  ('123rhaxld', '최도랑', 'https://profile.img.sooplive.co.kr/LOGO/12/123rhaxld/123rhaxld.jpg', '뉴켓슬'),
  ('2ahgo1203', '이아깽', 'https://profile.img.sooplive.co.kr/LOGO/2a/2ahgo1203/2ahgo1203.jpg', '뉴켓슬'),
  ('tndkekdy', '하윤', 'https://profile.img.sooplive.co.kr/LOGO/tn/tndkekdy/tndkekdy.jpg', '뉴켓슬'),
  ('killkg2', '김건욱', 'https://profile.img.sooplive.co.kr/LOGO/ki/killkg2/killkg2.jpg', '뉴켓슬'),
  ('queenzu', '퀸주', 'https://profile.img.sooplive.co.kr/LOGO/qu/queenzu/queenzu.jpg', '뉴켓슬'),
  ('corgi1102', '냥냥코기', 'https://profile.img.sooplive.co.kr/LOGO/co/corgi1102/corgi1102.jpg', '뉴켓슬'),
  ('ksmo54', '구라미스', 'https://profile.img.sooplive.co.kr/LOGO/ks/ksmo54/ksmo54.jpg', '뉴켓슬'),
  ('parkle1006', '박듀듀', 'https://profile.img.sooplive.co.kr/LOGO/pa/parkle1006/parkle1006.jpg', '뉴켓슬'),
  ('wodnrdldia', '도재욱', 'https://profile.img.sooplive.co.kr/LOGO/wo/wodnrdldia/wodnrdldia.jpg', '뉴켓슬'),
  ('dbwjdcool1', '키링', 'https://profile.img.sooplive.co.kr/LOGO/db/dbwjdcool1/dbwjdcool1.jpg', '뉴켓슬'),
  ('jun10280', '박성준', 'https://profile.img.sooplive.co.kr/LOGO/ju/jun10280/jun10280.jpg', '뉴켓슬'),
  ('1004yomi', '단솔', 'https://profile.img.sooplive.co.kr/LOGO/10/1004yomi/1004yomi.jpg', '뉴켓슬'),
  ('qwer1317', '으니', 'https://profile.img.sooplive.co.kr/LOGO/qw/qwer1317/qwer1317.jpg', '뉴켓슬'),
  ('aybjc2319', '진유성', 'https://profile.img.sooplive.co.kr/LOGO/ay/aybjc2319/aybjc2319.jpg', '뉴켓슬'),
  ('peros777', '박성균', 'https://profile.img.sooplive.co.kr/LOGO/pe/peros777/peros777.jpg', '뉴켓슬'),
  ('totoo23', '밍또얌', 'https://profile.img.sooplive.co.kr/LOGO/to/totoo23/totoo23.jpg', '뉴켓슬'),
  ('zzzz809', '백갑숙', 'https://profile.img.sooplive.co.kr/LOGO/zz/zzzz809/zzzz809.jpg', '뉴켓슬'),
  ('dbrbals', '초난강', 'https://profile.img.sooplive.co.kr/LOGO/db/dbrbals/dbrbals.jpg', '뉴켓슬'),
  ('ywww123', '트슈', 'https://profile.img.sooplive.co.kr/LOGO/yw/ywww123/ywww123.jpg', '뉴켓슬'),
  ('dmk1212', '액션구드론', 'https://profile.img.sooplive.co.kr/LOGO/dm/dmk1212/dmk1212.jpg', '뉴켓슬'),
  ('freshtomato', '토마토', 'https://profile.img.sooplive.co.kr/LOGO/fr/freshtomato/freshtomato.jpg', '캄몬'),
  ('seemin88', '비타밍', 'https://profile.img.sooplive.co.kr/LOGO/se/seemin88/seemin88.jpg', '캄몬'),
  ('wjswlgns09', '지두두', 'https://profile.img.sooplive.co.kr/LOGO/wj/wjswlgns09/wjswlgns09.jpg', '캄몬'),
  ('sksmsskdsl10', '낭니', 'https://profile.img.sooplive.co.kr/LOGO/sk/sksmsskdsl10/sksmsskdsl10.jpg', '캄몬'),
  ('fpahsdltu1', '주하랑', 'https://profile.img.sooplive.co.kr/LOGO/fp/fpahsdltu1/fpahsdltu1.jpg', '캄몬'),
  ('rnaqpdrjf', '남덕선', 'https://profile.img.sooplive.co.kr/LOGO/rn/rnaqpdrjf/rnaqpdrjf.jpg', '캄몬'),
  ('dlaguswl501', '임조이', 'https://profile.img.sooplive.co.kr/LOGO/dl/dlaguswl501/dlaguswl501.jpg', '캄몬'),
  ('vldpfm2', '아리송이', 'https://profile.img.sooplive.co.kr/LOGO/vl/vldpfm2/vldpfm2.jpg', '캄몬'),
  ('2meonjin', '먼진', 'https://profile.img.sooplive.co.kr/LOGO/2m/2meonjin/2meonjin.jpg', '캄몬'),
  ('thelddl', '햇살', 'https://profile.img.sooplive.co.kr/LOGO/th/thelddl/thelddl.jpg', '캄몬'),
  ('h78ert', '박준오', 'https://profile.img.sooplive.co.kr/LOGO/h7/h78ert/h78ert.jpg', '캄몬'),
  ('hoonykkk', '사테', 'https://profile.img.sooplive.co.kr/LOGO/ho/hoonykkk/hoonykkk.jpg', '캄몬'),
  ('soju2022', '소주양', 'https://profile.img.sooplive.co.kr/LOGO/so/soju2022/soju2022.jpg', '캄몬'),
  ('jmc06170', '왜냐맨', 'https://profile.img.sooplive.co.kr/LOGO/jm/jmc06170/jmc06170.jpg', '캄몬'),
  ('minchul', '김민철', 'https://profile.img.sooplive.co.kr/LOGO/mi/minchul/minchul.jpg', '캄몬'),
  ('goodzerg', '배성흠', 'https://profile.img.sooplive.co.kr/LOGO/go/goodzerg/goodzerg.jpg', '캄몬'),
  ('seul0316', '슬돌이', 'https://profile.img.sooplive.co.kr/LOGO/se/seul0316/seul0316.jpg', '케이대'),
  ('jooyoung0040', '또아', 'https://profile.img.sooplive.co.kr/LOGO/jo/jooyoung0040/jooyoung0040.jpg', '케이대'),
  ('goni2677', '내가먼지', 'https://profile.img.sooplive.co.kr/LOGO/go/goni2677/goni2677.jpg', '케이대'),
  ('skygkrtn', '김학수', 'https://profile.img.sooplive.co.kr/LOGO/sk/skygkrtn/skygkrtn.jpg', '케이대'),
  ('qkrgkdms01', '박하악', 'https://profile.img.sooplive.co.kr/LOGO/qk/qkrgkdms01/qkrgkdms01.jpg', '케이대'),
  ('clclcl8888', '늑대채린', 'https://profile.img.sooplive.co.kr/LOGO/cl/clclcl8888/clclcl8888.jpg', '케이대'),
  ('zcv0320', '보혜', 'https://profile.img.sooplive.co.kr/LOGO/zc/zcv0320/zcv0320.jpg', '케이대'),
  ('agah1106', '링고', 'https://profile.img.sooplive.co.kr/LOGO/ag/agah1106/agah1106.jpg', '케이대'),
  ('kjy3443', '연또', 'https://profile.img.sooplive.co.kr/LOGO/kj/kjy3443/kjy3443.jpg', '케이대'),
  ('ever316', '정소윤', 'https://profile.img.sooplive.co.kr/LOGO/ev/ever316/ever316.jpg', '케이대'),
  ('seols2', '정서린', 'https://profile.img.sooplive.co.kr/LOGO/se/seols2/seols2.jpg', '케이대'),
  ('tmsh401', '장윤철', 'https://profile.img.sooplive.co.kr/LOGO/tm/tmsh401/tmsh401.jpg', '케이대'),
  ('neverdieyj', '정영재', 'https://profile.img.sooplive.co.kr/LOGO/ne/neverdieyj/neverdieyj.jpg', '케이대'),
  ('hongduck9737', '홍덕', 'https://profile.img.sooplive.co.kr/LOGO/ho/hongduck9737/hongduck9737.jpg', '케이대'),
  ('kkmkhh1234', '깨모다', 'https://profile.img.sooplive.co.kr/LOGO/kk/kkmkhh1234/kkmkhh1234.jpg', '케이대'),
  ('minyoo3972', '유민', 'https://profile.img.sooplive.co.kr/LOGO/mi/minyoo3972/minyoo3972.jpg', '케이대'),
  ('wjdalsrl95', '정민기', 'https://profile.img.sooplive.co.kr/LOGO/wj/wjdalsrl95/wjdalsrl95.jpg', '케이대'),
  ('understay', '고석현', 'https://profile.img.sooplive.co.kr/LOGO/un/understay/understay.jpg', '케이대'),
  ('wittyku', '냥수디', 'https://profile.img.sooplive.co.kr/LOGO/wi/wittyku/wittyku.jpg', '케이대'),
  ('thdeksql', '단비송', 'https://profile.img.sooplive.co.kr/LOGO/th/thdeksql/thdeksql.jpg', '케이대'),
  ('meezmeun', '미지믄', 'https://profile.img.sooplive.co.kr/LOGO/me/meezmeun/meezmeun.jpg', '케이대'),
  ('gpfl5473', '히리캉', 'https://profile.img.sooplive.co.kr/LOGO/gp/gpfl5473/gpfl5473.jpg', '케이대'),
  ('skdidkfl', '♥김아린', 'https://profile.img.sooplive.co.kr/LOGO/sk/skdidkfl/skdidkfl.jpg', '케이대'),
  ('jelly97', '찌효', 'https://profile.img.sooplive.co.kr/LOGO/je/jelly97/jelly97.jpg', '케이대'),
  ('whitedaysen', '세니-.-', 'https://profile.img.sooplive.co.kr/LOGO/wh/whitedaysen/whitedaysen.jpg', '케이대'),
  ('nvbn114', '♥앙혜원', 'https://profile.img.sooplive.co.kr/LOGO/nv/nvbn114/nvbn114.jpg', '케이대'),
  ('gddms97', '하블리', 'https://profile.img.sooplive.co.kr/LOGO/gd/gddms97/gddms97.jpg', 'JSA'),
  ('littlekim12', '김바다', 'https://profile.img.sooplive.co.kr/LOGO/li/littlekim12/littlekim12.jpg', 'JSA'),
  ('wlgua7272', '2라니', 'https://profile.img.sooplive.co.kr/LOGO/wl/wlgua7272/wlgua7272.jpg', 'JSA'),
  ('wjddmstj79', '쟈닌', 'https://profile.img.sooplive.co.kr/LOGO/wj/wjddmstj79/wjddmstj79.jpg', 'JSA'),
  ('tamama88', '타마양', 'https://profile.img.sooplive.co.kr/LOGO/ta/tamama88/tamama88.jpg', 'JSA'),
  ('phh95426', '소심', 'https://profile.img.sooplive.co.kr/LOGO/ph/phh95426/phh95426.jpg', 'JSA'),
  ('fudnjs0235', '려원', 'https://profile.img.sooplive.co.kr/LOGO/fu/fudnjs0235/fudnjs0235.jpg', 'JSA'),
  ('dpfgc3', '홍구', 'https://profile.img.sooplive.co.kr/LOGO/dp/dpfgc3/dpfgc3.jpg', 'JSA'),
  ('owoouoowo', '모비', 'https://profile.img.sooplive.co.kr/LOGO/ow/owoouoowo/owoouoowo.jpg', 'JSA'),
  ('tjdeosks', '김성대', 'https://profile.img.sooplive.co.kr/LOGO/tj/tjdeosks/tjdeosks.jpg', 'JSA'),
  ('rldyal71', '휘연', 'https://profile.img.sooplive.co.kr/LOGO/rl/rldyal71/rldyal71.jpg', 'JSA'),
  ('min030606', '면추가', 'https://profile.img.sooplive.co.kr/LOGO/mi/min030606/min030606.jpg', 'JSA'),
  ('dgh9641', '김병수', 'https://profile.img.sooplive.co.kr/LOGO/dg/dgh9641/dgh9641.jpg', 'JSA'),
  ('ftrudals', '나린', 'https://profile.img.sooplive.co.kr/LOGO/ft/ftrudals/ftrudals.jpg', 'JSA'),
  ('sharpragu', '조기석', 'https://profile.img.sooplive.co.kr/LOGO/sh/sharpragu/sharpragu.jpg', 'JSA'),
  ('rladuddo99', '구성훈', 'https://profile.img.sooplive.co.kr/LOGO/rl/rladuddo99/rladuddo99.jpg', 'JSA'),
  ('shyshy123', '김영진', 'https://profile.img.sooplive.co.kr/LOGO/sh/shyshy123/shyshy123.jpg', 'JSA'),
  ('dkfka8945', '라미', 'https://profile.img.sooplive.co.kr/LOGO/dk/dkfka8945/dkfka8945.jpg', 'JSA'),
  ('vhrtmspt', '김민우', 'https://profile.img.sooplive.co.kr/LOGO/vh/vhrtmspt/vhrtmspt.jpg', 'JSA'),
  ('dyaan0v0', '정다닝', 'https://profile.img.sooplive.co.kr/LOGO/dy/dyaan0v0/dyaan0v0.jpg', 'JSA'),
  ('begoniah', '백원이야', 'https://profile.img.sooplive.co.kr/LOGO/be/begoniah/begoniah.jpg', 'JSA'),
  ('tato1104', '밍가', 'https://profile.img.sooplive.co.kr/LOGO/ta/tato1104/tato1104.jpg', '광준'),
  ('rlsk0705', '기나', 'https://profile.img.sooplive.co.kr/LOGO/rl/rlsk0705/rlsk0705.jpg', '광준'),
  ('cyj982002', '다나짱', 'https://profile.img.sooplive.co.kr/LOGO/cy/cyj982002/cyj982002.jpg', '광준'),
  ('dmswls4565', '공다츠', 'https://profile.img.sooplive.co.kr/LOGO/dm/dmswls4565/dmswls4565.jpg', '광준'),
  ('rondobba', '지동원', 'https://profile.img.sooplive.co.kr/LOGO/ro/rondobba/rondobba.jpg', '광준'),
  ('chuwari13', '요구리', 'https://profile.img.sooplive.co.kr/LOGO/ch/chuwari13/chuwari13.jpg', '광준'),
  ('fidfidfid', '박쭈이', 'https://profile.img.sooplive.co.kr/LOGO/fi/fidfidfid/fidfidfid.jpg', '광준'),
  ('qndnd12', '김기덕', 'https://profile.img.sooplive.co.kr/LOGO/qn/qndnd12/qndnd12.jpg', '광준'),
  ('pazzy1', '파찌', 'https://profile.img.sooplive.co.kr/LOGO/pa/pazzy1/pazzy1.jpg', '광준'),
  ('tjgpdus97', '요닝', 'https://profile.img.sooplive.co.kr/LOGO/tj/tjgpdus97/tjgpdus97.jpg', '드림즈'),
  ('alaelddl97', '민지', 'https://profile.img.sooplive.co.kr/LOGO/al/alaelddl97/alaelddl97.jpg', '드림즈'),
  ('nreupne', '핑핑', 'https://profile.img.sooplive.co.kr/LOGO/nr/nreupne/nreupne.jpg', '드림즈'),
  ('wlswn6565', '진땅콩', 'https://profile.img.sooplive.co.kr/LOGO/wl/wlswn6565/wlswn6565.jpg', '드림즈'),
  ('imducko3o', '오리꿍', 'https://profile.img.sooplive.co.kr/LOGO/im/imducko3o/imducko3o.jpg', '드림즈'),
  ('ys9024', '주서리', 'https://profile.img.sooplive.co.kr/LOGO/ys/ys9024/ys9024.jpg', '드림즈'),
  ('queen030', '효짱', 'https://profile.img.sooplive.co.kr/LOGO/qu/queen030/queen030.jpg', '드림즈'),
  ('viwi05', '럭키위키', 'https://profile.img.sooplive.co.kr/LOGO/vi/viwi05/viwi05.jpg', '드림즈'),
  ('j4141h', '요괴버스', 'https://profile.img.sooplive.co.kr/LOGO/j4/j4141h/j4141h.jpg', '드림즈'),
  ('kuyol', '강구열', 'https://profile.img.sooplive.co.kr/LOGO/ku/kuyol/kuyol.jpg', '드림즈'),
  ('djdbstn', '어윤수', 'https://profile.img.sooplive.co.kr/LOGO/dj/djdbstn/djdbstn.jpg', '드림즈'),
  ('dbsdydx', '윤용태', 'https://profile.img.sooplive.co.kr/LOGO/db/dbsdydx/dbsdydx.jpg', '드림즈'),
  ('hby0724', '황병영', 'https://profile.img.sooplive.co.kr/LOGO/hb/hby0724/hby0724.jpg', '드림즈'),
  ('kss33325', '김수식', 'https://profile.img.sooplive.co.kr/LOGO/ks/kss33325/kss33325.jpg', '드림즈'),
  ('wjswpalssla1', '전제민', 'https://profile.img.sooplive.co.kr/LOGO/wj/wjswpalssla1/wjswpalssla1.jpg', '드림즈'),
  ('moguleave', '모리', 'https://profile.img.sooplive.co.kr/LOGO/mo/moguleave/moguleave.jpg', '드림즈'),
  ('kimp1ay', '구키', 'https://profile.img.sooplive.co.kr/LOGO/ki/kimp1ay/kimp1ay.jpg', '와플대'),
  ('hee4343', '비재희', 'https://profile.img.sooplive.co.kr/LOGO/he/hee4343/hee4343.jpg', '와플대'),
  ('daegalheo', '허유', 'https://profile.img.sooplive.co.kr/LOGO/da/daegalheo/daegalheo.jpg', '와플대'),
  ('byebye22', '에공', 'https://profile.img.sooplive.co.kr/LOGO/by/byebye22/byebye22.jpg', '와플대'),
  ('snowssa', '설둥이', 'https://profile.img.sooplive.co.kr/LOGO/sn/snowssa/snowssa.jpg', '와플대'),
  ('nylove276', '삐약비약', 'https://profile.img.sooplive.co.kr/LOGO/ny/nylove276/nylove276.jpg', '와플대'),
  ('gkgus99', '하이현', 'https://profile.img.sooplive.co.kr/LOGO/gk/gkgus99/gkgus99.jpg', '와플대'),
  ('dlwjddls30', '야생땃쥐', 'https://profile.img.sooplive.co.kr/LOGO/dl/dlwjddls30/dlwjddls30.jpg', '와플대'),
  ('asdsa1113', '세월', 'https://profile.img.sooplive.co.kr/LOGO/as/asdsa1113/asdsa1113.jpg', '와플대'),
  ('jhyhlli123', '박준혁', 'https://profile.img.sooplive.co.kr/LOGO/jh/jhyhlli123/jhyhlli123.jpg', '와플대'),
  ('wnsgur2da', '압삽e', 'https://profile.img.sooplive.co.kr/LOGO/wn/wnsgur2da/wnsgur2da.jpg', '와플대'),
  ('youaregood', '진니', 'https://profile.img.sooplive.co.kr/LOGO/yo/youaregood/youaregood.jpg', '와플대'),
  ('e2003jin', '여지니', 'https://profile.img.sooplive.co.kr/LOGO/e2/e2003jin/e2003jin.jpg', '와플대'),
  ('shj06170', '얌쭈', 'https://profile.img.sooplive.co.kr/LOGO/sh/shj06170/shj06170.jpg', '와플대'),
  ('ldk8481', '슈슈', 'https://profile.img.sooplive.co.kr/LOGO/ld/ldk8481/ldk8481.jpg', 'BGM'),
  ('dudwn4974', '안아', 'https://profile.img.sooplive.co.kr/LOGO/du/dudwn4974/dudwn4974.jpg', 'BGM'),
  ('kitty1029', '꼬니부깅', 'https://profile.img.sooplive.co.kr/LOGO/ki/kitty1029/kitty1029.jpg', 'BGM'),
  ('dmsgkdn12', '엔돌핀', 'https://profile.img.sooplive.co.kr/LOGO/dm/dmsgkdn12/dmsgkdn12.jpg', 'BGM'),
  ('janjanoo', '진서랄까', 'https://profile.img.sooplive.co.kr/LOGO/ja/janjanoo/janjanoo.jpg', 'BGM'),
  ('totlllsz', '몽순', 'https://profile.img.sooplive.co.kr/LOGO/to/totlllsz/totlllsz.jpg', 'BGM'),
  ('happyhee97', '예담', 'https://profile.img.sooplive.co.kr/LOGO/ha/happyhee97/happyhee97.jpg', 'BGM'),
  ('hy4985', '뽀누나', 'https://profile.img.sooplive.co.kr/LOGO/hy/hy4985/hy4985.jpg', 'BGM'),
  ('bumsoo552', '김범수', 'https://profile.img.sooplive.co.kr/LOGO/bu/bumsoo552/bumsoo552.jpg', 'BGM'),
  ('eeceec', '뚜미', 'https://profile.img.sooplive.co.kr/LOGO/ee/eeceec/eeceec.jpg', 'BGM'),
  ('wkddudrms15', '난수', 'https://profile.img.sooplive.co.kr/LOGO/wk/wkddudrms15/wkddudrms15.jpg', 'BGM'),
  ('dmsthfdldia', '라운이', 'https://profile.img.sooplive.co.kr/LOGO/dm/dmsthfdldia/dmsthfdldia.jpg', 'BGM'),
  ('xzqwe1', '황단비', 'https://profile.img.sooplive.co.kr/LOGO/xz/xzqwe1/xzqwe1.jpg', 'BGM'),
  ('lky6407', '프발', 'https://profile.img.sooplive.co.kr/LOGO/lk/lky6407/lky6407.jpg', 'BGM'),
  ('jh3697', '서문지훈', 'https://profile.img.sooplive.co.kr/LOGO/jh/jh3697/jh3697.jpg', 'BGM'),
  ('nada11200', '이윤열', 'https://profile.img.sooplive.co.kr/LOGO/na/nada11200/nada11200.jpg', 'BGM'),
  ('ghlidhjgioew', '다라츄', 'https://profile.img.sooplive.co.kr/LOGO/gh/ghlidhjgioew/ghlidhjgioew.jpg', 'BGM'),
  ('have1y', '김채이', 'https://profile.img.sooplive.co.kr/LOGO/ha/have1y/have1y.jpg', '마범대'),
  ('rabbitmiffy', '최세상', 'https://profile.img.sooplive.co.kr/LOGO/ra/rabbitmiffy/rabbitmiffy.jpg', '마범대'),
  ('arr0530', '권아온', 'https://profile.img.sooplive.co.kr/LOGO/ar/arr0530/arr0530.jpg', '마범대'),
  ('pengmuin', '민댕댕', 'https://profile.img.sooplive.co.kr/LOGO/pe/pengmuin/pengmuin.jpg', '마범대'),
  ('hamhee', '햄희', 'https://profile.img.sooplive.co.kr/LOGO/ha/hamhee/hamhee.jpg', '마범대'),
  ('heyyo0123', '헤요이', 'https://profile.img.sooplive.co.kr/LOGO/he/heyyo0123/heyyo0123.jpg', '마범대'),
  ('ehcl000', '또치', 'https://profile.img.sooplive.co.kr/LOGO/eh/ehcl000/ehcl000.jpg', '마범대'),
  ('hasaeyo', '안눙이', 'https://profile.img.sooplive.co.kr/LOGO/ha/hasaeyo/hasaeyo.jpg', '마범대'),
  ('lyh8808', '이영한', 'https://profile.img.sooplive.co.kr/LOGO/ly/lyh8808/lyh8808.jpg', '마범대'),
  ('synyoung', '시녕뭉', 'https://profile.img.sooplive.co.kr/LOGO/sy/synyoung/synyoung.jpg', '마범대'),
  ('jackpot', '이창우', 'https://profile.img.sooplive.co.kr/LOGO/ja/jackpot/jackpot.jpg', '마범대'),
  ('paralyze92', '정경두', 'https://profile.img.sooplive.co.kr/LOGO/pa/paralyze92/paralyze92.jpg', '마범대'),
  ('askl021', '빡죠스', 'https://profile.img.sooplive.co.kr/LOGO/as/askl021/askl021.jpg', '마범대'),
  ('rlarnfk24', '만두호성', 'https://profile.img.sooplive.co.kr/LOGO/rl/rlarnfk24/rlarnfk24.jpg', '마범대'),
  ('ghkdud1617', '카히리', 'https://profile.img.sooplive.co.kr/LOGO/gh/ghkdud1617/ghkdud1617.jpg', '마범대'),
  ('bora99', '구보라', 'https://profile.img.sooplive.co.kr/LOGO/bo/bora99/bora99.jpg', '마범대'),
  ('ovoa3316', '나예리', 'https://profile.img.sooplive.co.kr/LOGO/ov/ovoa3316/ovoa3316.jpg', '흑카데미'),
  ('lingolinga', '링가', 'https://profile.img.sooplive.co.kr/LOGO/li/lingolinga/lingolinga.jpg', '흑카데미'),
  ('gangeda', '갱이다', 'https://profile.img.sooplive.co.kr/LOGO/ga/gangeda/gangeda.jpg', '흑카데미'),
  ('faker1004', '가영', 'https://profile.img.sooplive.co.kr/LOGO/fa/faker1004/faker1004.jpg', '흑카데미'),
  ('ehgmldud1233', '히엉', 'https://profile.img.sooplive.co.kr/LOGO/eh/ehgmldud1233/ehgmldud1233.jpg', '흑카데미'),
  ('jhpark7712', '빡재', 'https://profile.img.sooplive.co.kr/LOGO/jh/jhpark7712/jhpark7712.jpg', '흑카데미'),
  ('tjwjddms1565', '선정은', 'https://profile.img.sooplive.co.kr/LOGO/tj/tjwjddms1565/tjwjddms1565.jpg', '흑카데미'),
  ('dollooo', '제갈츄빈', 'https://profile.img.sooplive.co.kr/LOGO/do/dollooo/dollooo.jpg', '흑카데미'),
  ('x1aohongmao', '오세은', 'https://profile.img.sooplive.co.kr/LOGO/x1/x1aohongmao/x1aohongmao.jpg', '흑카데미'),
  ('skarbwhgc', '팔레트', 'https://profile.img.sooplive.co.kr/LOGO/sk/skarbwhgc/skarbwhgc.jpg', '흑카데미'),
  ('rudzhd123', '경콩', 'https://profile.img.sooplive.co.kr/LOGO/ru/rudzhd123/rudzhd123.jpg', '흑카데미'),
  ('yuna1024', '김유나', 'https://profile.img.sooplive.co.kr/LOGO/yu/yuna1024/yuna1024.jpg', '흑카데미'),
  ('bhy95', '배호딱', 'https://profile.img.sooplive.co.kr/LOGO/bh/bhy95/bhy95.jpg', '흑카데미'),
  ('scan1014', '유승곤', 'https://profile.img.sooplive.co.kr/LOGO/sc/scan1014/scan1014.jpg', '흑카데미'),
  ('ndudska620', '달그락영주', 'https://profile.img.sooplive.co.kr/LOGO/nd/ndudska620/ndudska620.jpg', '흑카데미'),
  ('kwh1992', '우힝이', 'https://profile.img.sooplive.co.kr/LOGO/kw/kwh1992/kwh1992.jpg', '흑카데미'),
  ('chchchshai', '유이', 'https://profile.img.sooplive.co.kr/LOGO/ch/chchchshai/chchchshai.jpg', '흑카데미'),
  ('maeong2', '메옹', 'https://profile.img.sooplive.co.kr/LOGO/ma/maeong2/maeong2.jpg', '흑카데미'),
  ('lovelove7777', '서지수', 'https://profile.img.sooplive.co.kr/LOGO/lo/lovelove7777/lovelove7777.jpg', 'DM'),
  ('5eulgii', '김말랑', 'https://profile.img.sooplive.co.kr/LOGO/5e/5eulgii/5eulgii.jpg', 'DM'),
  ('gnsl418', '이예훈', 'https://profile.img.sooplive.co.kr/LOGO/gn/gnsl418/gnsl418.jpg', 'DM'),
  ('jscando77', '빵리나', 'https://profile.img.sooplive.co.kr/LOGO/js/jscando77/jscando77.jpg', 'DM'),
  ('nasd06', '수니양', 'https://profile.img.sooplive.co.kr/LOGO/na/nasd06/nasd06.jpg', 'DM'),
  ('gkdud3294', '오하얀', 'https://profile.img.sooplive.co.kr/LOGO/gk/gkdud3294/gkdud3294.jpg', 'DM'),
  ('eunseo0152', '은서', 'https://profile.img.sooplive.co.kr/LOGO/eu/eunseo0152/eunseo0152.jpg', 'DM'),
  ('lily0104', '정소이', 'https://profile.img.sooplive.co.kr/LOGO/li/lily0104/lily0104.jpg', 'DM'),
  ('zealot0846', '원선재', 'https://profile.img.sooplive.co.kr/LOGO/ze/zealot0846/zealot0846.jpg', 'DM'),
  ('danu619', '다뉴', 'https://profile.img.sooplive.co.kr/LOGO/da/danu619/danu619.jpg', 'DM'),
  ('eunjo0105', '은조', 'https://profile.img.sooplive.co.kr/LOGO/eu/eunjo0105/eunjo0105.jpg', 'DM'),
  ('jiwooris2', '지우리', 'https://profile.img.sooplive.co.kr/LOGO/ji/jiwooris2/jiwooris2.jpg', '신세계'),
  ('dohyeon97', '선우도현', 'https://profile.img.sooplive.co.kr/LOGO/do/dohyeon97/dohyeon97.jpg', '신세계'),
  ('khl1589', '요시', 'https://profile.img.sooplive.co.kr/LOGO/kh/khl1589/khl1589.jpg', '신세계'),
  ('finepearls', '혜냥', 'https://profile.img.sooplive.co.kr/LOGO/fi/finepearls/finepearls.jpg', '신세계'),
  ('rnjsgurwls15', '권혁진', 'https://profile.img.sooplive.co.kr/LOGO/rn/rnjsgurwls15/rnjsgurwls15.jpg', '신세계'),
  ('cksgmldbs', '몽군', 'https://profile.img.sooplive.co.kr/LOGO/ck/cksgmldbs/cksgmldbs.jpg', '신세계'),
  ('haeun5513', '밤하밍', 'https://profile.img.sooplive.co.kr/LOGO/ha/haeun5513/haeun5513.jpg', '신세계'),
  ('djathekd', '연예인', 'https://profile.img.sooplive.co.kr/LOGO/dj/djathekd/djathekd.jpg', '신세계'),
  ('snfjdro369', '윤수철', 'https://profile.img.sooplive.co.kr/LOGO/sn/snfjdro369/snfjdro369.jpg', '신세계'),
  ('simcheong23', '또봉순', 'https://profile.img.sooplive.co.kr/LOGO/si/simcheong23/simcheong23.jpg', '신세계'),
  ('della2440', '예실', 'https://profile.img.sooplive.co.kr/LOGO/de/della2440/della2440.jpg', '신세계'),
  ('jjjjeong', '태린', 'https://profile.img.sooplive.co.kr/LOGO/jj/jjjjeong/jjjjeong.jpg', '소병대'),
  ('chanmeyo', '김세주', 'https://profile.img.sooplive.co.kr/LOGO/ch/chanmeyo/chanmeyo.jpg', '소병대'),
  ('rlawhdwns6', '멍이', 'https://profile.img.sooplive.co.kr/LOGO/rl/rlawhdwns6/rlawhdwns6.jpg', '소병대'),
  ('rnfma14', '김설', 'https://profile.img.sooplive.co.kr/LOGO/rn/rnfma14/rnfma14.jpg', '소병대'),
  ('byromantic', '최재성', 'https://profile.img.sooplive.co.kr/LOGO/by/byromantic/byromantic.jpg', '소병대'),
  ('janghoman', '베트남테란', 'https://profile.img.sooplive.co.kr/LOGO/ja/janghoman/janghoman.jpg', '소병대'),
  ('bwstar', '배병우', 'https://profile.img.sooplive.co.kr/LOGO/bw/bwstar/bwstar.jpg', '소병대'),
  ('dkswjddn92', '안정우', 'https://profile.img.sooplive.co.kr/LOGO/dk/dkswjddn92/dkswjddn92.jpg', '소병대'),
  ('tjdwnls123', '박성진', 'https://profile.img.sooplive.co.kr/LOGO/tj/tjdwnls123/tjdwnls123.jpg', '소병대'),
  ('zinsim', '봄덕이', 'https://profile.img.sooplive.co.kr/LOGO/zi/zinsim/zinsim.jpg', '소병대'),
  ('yyssaa33', '제티♥', 'https://profile.img.sooplive.co.kr/LOGO/yy/yyssaa33/yyssaa33.jpg', '소병대'),
  ('parkbano', '시라소니aa', 'https://profile.img.sooplive.co.kr/LOGO/pa/parkbano/parkbano.jpg', '소병대')
)
INSERT INTO public.streamers (soop_id, nickname, profile_image_url, crew_id, is_active)
SELECT roster.soop_id, roster.nickname, roster.profile_image_url, crews.id, true
FROM roster
JOIN public.crews AS crews ON crews.name = roster.crew_name
ON CONFLICT (soop_id) DO UPDATE SET
  nickname = EXCLUDED.nickname,
  profile_image_url = EXCLUDED.profile_image_url,
  crew_id = EXCLUDED.crew_id,
  is_active = true;
